spring:
  datasource:
    url: jdbc:mysql://local.dev:3306/carp_ddd?useUnicode=true&characterEncoding=utf8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678

  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
