server:
  port: 8000

spring:
  application:
    name: carp-ums
  profiles:
    include: redis,jdbc,mybatis,feign
  cloud:
    zookeeper:
      connect-string: test.dev:2181
      discovery:
        enabled: true
logging:
  config: classpath:config/properties/log4j2.properties
  file:
    path: logs
