carp:
  security:
    oauth2:
      resource:
        enable: true
        whitelabel-clients: carp
        whitelabel-urls:
          #内部接口加密但不拦截
          - /feign/**
          #swagger接口
          - /doc/api/**
          - /swagger-ui.html
          - /webjars/**
          - /swagger-resources/**
          - /v2/api-docs/**

security:
  oauth2:
    client:
      client-id: carp
      client-secret: carp
    resource:
      id: carp-ums
      token-info-uri: http://carp-auth:8002/oauth2/token/check
      loadBalanced: true
