spring:
  datasource:
    url: jdbc:mysql://carp-dev:3306/carp_ddd?useUnicode=true&characterEncoding=utf8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
