server:
  port: 8010
spring:
  application:
    name: carp-common-rocketmq
rocketmq:
  name-server: carp-dev:9876
  producer:
    group: GID_carp_rocketmq2
    customized-trace-topic: Topic_carp_rocketmq

carp:
  eventbus:
    rocketmq:
      group: GID_carp_rocketmq
      topic: Topic_carp_rocketmq