server:
  port: 8010
spring:
  application:
    name: carp-common-rocketmq
rocketmq:
  name-server: carp-dev:9876
  producer:
    group: GID_carp_rocketmq

carp:
  eventbus:
    rocketmq:
      group: GID_carp_eventbus
      topic: Topic_carp_eventbus