server:
  port: 8010
spring:
  application:
    name: carp-common-rocketmq
rocketmq:
  name-server: carp-dev:9876
  producer:
    group: GID_carp_rocketmq
    customized-trace-topic: Topic_carp_rocketmq

mqeventbus:
  consumer:
    group: CID_carp_rocketmq
    customized-trace-topic: Topic_carp_rocketmq