leaf:
  segment:
    enable: true
    url: jdbc:mysql://carp-dev:3306/leaf?useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345678
  snowflake:
    enable: true
    address: carp-dev:2181
    port: 8280